name: login_page
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_theme_switcher: ^1.0.5
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.4
  firebase_core: 0.5.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  fluttertoast: ^7.1.5
  line_awesome_flutter: ^1.0.1
  qr_flutter: ^3.2.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: painter
      fonts:
        - asset: fonts/Painter-LxXg.ttf

    - family: montserrat
      fonts:
        - asset: fonts/MontserratAlternates-Bold.otf

    - family: montserrat1
      fonts:
        - asset: fonts/MontserratAlternates-Regular.otf
  # For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
